/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo;

import com.sun.management.jmx.Trace;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.util.ArrayList;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author aurk0
 */
public class zSystem extends javax.swing.JFrame {

    /**
     * Creates new form zSystem
     */
    
    public zSystem() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbedPanel = new javax.swing.JTabbedPane();
        Animal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        a4 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        a7 = new javax.swing.JCheckBox();
        a8 = new javax.swing.JCheckBox();
        a9 = new javax.swing.JCheckBox();
        a10 = new javax.swing.JCheckBox();
        a11 = new javax.swing.JCheckBox();
        a12 = new javax.swing.JCheckBox();
        a13 = new javax.swing.JCheckBox();
        aC1 = new javax.swing.JTextField();
        aC2 = new javax.swing.JTextField();
        aC3 = new javax.swing.JTextField();
        aC4 = new javax.swing.JTextField();
        aC5 = new javax.swing.JTextField();
        aC6 = new javax.swing.JTextField();
        aC7 = new javax.swing.JTextField();
        aC8 = new javax.swing.JTextField();
        aC9 = new javax.swing.JTextField();
        aC10 = new javax.swing.JTextField();
        aC11 = new javax.swing.JTextField();
        aC12 = new javax.swing.JTextField();
        aC13 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        allAni = new javax.swing.JButton();
        clearAll = new javax.swing.JButton();
        close = new javax.swing.JButton();
        result = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Food = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        q3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        totalVeg = new javax.swing.JButton();
        vegT = new javax.swing.JTextField();
        totalMeat = new javax.swing.JButton();
        meatT = new javax.swing.JTextField();
        Combo2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        close2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Receipt = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        clearTextF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        close3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Emergency = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ownerB = new javax.swing.JRadioButton();
        managerB = new javax.swing.JRadioButton();
        policeB = new javax.swing.JRadioButton();
        ownerN = new javax.swing.JTextField();
        managerN = new javax.swing.JTextField();
        policeN = new javax.swing.JTextField();
        SignOut = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(310, 518));

        Animal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(95, 97, 124));

        a1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a1.setForeground(new java.awt.Color(204, 204, 204));
        a1.setText(" Lion");

        a2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a2.setForeground(new java.awt.Color(204, 204, 204));
        a2.setText(" Tiger");

        a3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a3.setForeground(new java.awt.Color(204, 204, 204));
        a3.setText(" Rhino");

        a4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a4.setForeground(new java.awt.Color(204, 204, 204));
        a4.setText(" Aligator");

        a5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a5.setForeground(new java.awt.Color(204, 204, 204));
        a5.setText(" Monkey");

        a6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a6.setForeground(new java.awt.Color(204, 204, 204));
        a6.setText(" Panda");

        a7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a7.setForeground(new java.awt.Color(204, 204, 204));
        a7.setText(" Zebra");

        a8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a8.setForeground(new java.awt.Color(204, 204, 204));
        a8.setText(" Ostich");

        a9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a9.setForeground(new java.awt.Color(204, 204, 204));
        a9.setText(" Giraff");

        a10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a10.setForeground(new java.awt.Color(204, 204, 204));
        a10.setText(" Baboon");

        a11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a11.setForeground(new java.awt.Color(204, 204, 204));
        a11.setText("Beer");

        a12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a12.setForeground(new java.awt.Color(204, 204, 204));
        a12.setText(" Hippo");

        a13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a13.setForeground(new java.awt.Color(204, 204, 204));
        a13.setText(" Elephant");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a2)
                    .addComponent(a1)
                    .addComponent(a3)
                    .addComponent(a4)
                    .addComponent(a5)
                    .addComponent(a6)
                    .addComponent(a7)
                    .addComponent(a8)
                    .addComponent(a9)
                    .addComponent(a10)
                    .addComponent(a11)
                    .addComponent(a12)
                    .addComponent(a13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aC13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(aC12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(aC11)
                    .addComponent(aC10)
                    .addComponent(aC9)
                    .addComponent(aC8)
                    .addComponent(aC7)
                    .addComponent(aC6)
                    .addComponent(aC5)
                    .addComponent(aC4)
                    .addComponent(aC3)
                    .addComponent(aC1)
                    .addComponent(aC2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1)
                    .addComponent(aC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a2)
                    .addComponent(aC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a3)
                    .addComponent(aC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a4)
                    .addComponent(aC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a5)
                    .addComponent(aC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a6)
                    .addComponent(aC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a7)
                    .addComponent(aC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a8)
                    .addComponent(aC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a9)
                    .addComponent(aC9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a10)
                    .addComponent(aC10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a11)
                    .addComponent(aC11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a12)
                    .addComponent(aC12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a13)
                    .addComponent(aC13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        Animal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 260));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Animal List");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        Animal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        allAni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        allAni.setText("Total");
        allAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allAniActionPerformed(evt);
            }
        });
        Animal.add(allAni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 30));

        clearAll.setBackground(new java.awt.Color(51, 51, 255));
        clearAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearAll.setForeground(new java.awt.Color(255, 255, 255));
        clearAll.setText("Clear");
        clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllActionPerformed(evt);
            }
        });
        Animal.add(clearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 90, 30));

        close.setBackground(new java.awt.Color(255, 0, 51));
        close.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Exit");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        Animal.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 80, 30));
        Animal.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Available");
        Animal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Animals");
        Animal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/pea cock.jpg"))); // NOI18N
        Animal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        JTabbedPanel.addTab("Animal", Animal);

        Food.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Food Items");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Food.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Foods");
        Food.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vegetables");
        Food.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Peas", "Baby Corn", "Grass", "Cabbage", "Banana" }));
        Combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo1ActionPerformed(evt);
            }
        });
        Food.add(Combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Meat & Sushi");
        Food.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Need");
        Food.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("kg");
        Food.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Available");
        Food.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q2MouseClicked(evt);
            }
        });
        q2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                q2KeyPressed(evt);
            }
        });
        Food.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 60, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("kg");
        Food.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        Food.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 60, -1));

        q4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                q4KeyPressed(evt);
            }
        });
        Food.add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 60, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("kg");
        Food.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));
        Food.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 60, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("kg");
        Food.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));
        Food.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 60, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("tk");
        Food.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));
        Food.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 60, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("tk");
        Food.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        totalVeg.setBackground(new java.awt.Color(51, 51, 255));
        totalVeg.setForeground(new java.awt.Color(255, 255, 255));
        totalVeg.setText("Total");
        totalVeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalVegMouseClicked(evt);
            }
        });
        totalVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVegActionPerformed(evt);
            }
        });
        Food.add(totalVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        Food.add(vegT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 60, -1));

        totalMeat.setBackground(new java.awt.Color(51, 51, 255));
        totalMeat.setForeground(new java.awt.Color(255, 255, 255));
        totalMeat.setText("Total");
        totalMeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalMeatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                totalMeatMouseEntered(evt);
            }
        });
        totalMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMeatActionPerformed(evt);
            }
        });
        Food.add(totalMeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));
        Food.add(meatT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 60, -1));

        Combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Beef", "Chicken", "Mutton", "Fish" }));
        Combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo2ActionPerformed(evt);
            }
        });
        Food.add(Combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("tk");
        Food.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("tk");
        Food.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Available");
        Food.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Quantity");
        Food.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        Food.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 60, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("kg");
        Food.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        Food.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 60, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("kg");
        Food.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        close2.setBackground(new java.awt.Color(255, 0, 51));
        close2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        close2.setForeground(new java.awt.Color(255, 255, 255));
        close2.setText("Exit");
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });
        Food.add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 80, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Wild-Animal-Close-Zoo-Giraffes-Food-Animals-Head-537134.jpg"))); // NOI18N
        Food.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        JTabbedPanel.addTab("Food", Food);

        Receipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt.setEditable(false);
        receipt.setBackground(new java.awt.Color(230, 230, 230));
        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane2.setViewportView(receipt);

        Receipt.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 361));

        clearTextF.setBackground(new java.awt.Color(51, 51, 255));
        clearTextF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearTextF.setForeground(new java.awt.Color(255, 255, 255));
        clearTextF.setText("Clear Field");
        clearTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextFActionPerformed(evt);
            }
        });
        Receipt.add(clearTextF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 91, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Receipt");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        Receipt.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, 30));

        close3.setBackground(new java.awt.Color(255, 0, 51));
        close3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        close3.setForeground(new java.awt.Color(255, 255, 255));
        close3.setText("Exit");
        close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close3ActionPerformed(evt);
            }
        });
        Receipt.add(close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/burgerville.jpg"))); // NOI18N
        Receipt.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        JTabbedPanel.addTab("Receipt", Receipt);

        Emergency.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(194, 19, 19));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Emergency Call List");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        ownerB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ownerB.setText("Owner");
        ownerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerBActionPerformed(evt);
            }
        });

        managerB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        managerB.setText("Manager");
        managerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBActionPerformed(evt);
            }
        });

        policeB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        policeB.setText("Police");
        policeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeBActionPerformed(evt);
            }
        });

        ownerN.setText("0191-XXXXXXX");

        managerN.setText("0171-XXXXXXX");

        policeN.setText("0151-XXXXXXX");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownerB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerB)
                    .addComponent(policeB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(policeN)
                    .addComponent(managerN)
                    .addComponent(ownerN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerB)
                    .addComponent(ownerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerB)
                    .addComponent(managerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policeB)
                    .addComponent(policeN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        SignOut.setBackground(new java.awt.Color(255, 0, 0));
        SignOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setText("Sign Out");
        SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Call");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SignOut, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Emergency.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        JTabbedPanel.addTab("Emergency", Emergency);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabbedPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allAniActionPerformed
        // TODO add your handling code here:
        int all = 0;

        ArrayList<Integer> ani = new ArrayList<>();

        if(a1.isSelected()){
            aC1.setEditable(true);
            ani.add(Integer.parseInt(aC1.getText()));
        }
        if(a2.isSelected()){
            aC2.setEditable(true);
            ani.add(Integer.parseInt(aC2.getText()));
        }
        if(a3.isSelected()){
            aC3.setEditable(true);
            ani.add(Integer.parseInt(aC3.getText()));
        }
        if(a4.isSelected()){
            aC4.setEditable(true);
            ani.add(Integer.parseInt(aC4.getText()));
        }
        if(a5.isSelected()){
            aC5.setEnabled(true);
            ani.add(Integer.parseInt(aC5.getText()));
        }
        if(a6.isSelected()){
            aC6.setEditable(true);
            ani.add(Integer.parseInt(aC6.getText()));
        }
        if(a7.isSelected()){
            aC7.setEditable(true);
            ani.add(Integer.parseInt(aC7.getText()));
        }
        if(a8.isSelected()){
            aC8.setEditable(true);
            ani.add(Integer.parseInt(aC8.getText()));
        }
        if(a9.isSelected()){
            aC9.setEditable(true);
            ani.add(Integer.parseInt(aC9.getText()));
        }
        if(a10.isSelected()){
            aC10.setEditable(true);
            ani.add(Integer.parseInt(aC10.getText()));
        }
        if(a11.isSelected()){
            aC11.setEditable(true);
            ani.add(Integer.parseInt(aC11.getText()));
        }
        if(a12.isSelected()){
            aC12.setEditable(true);
            ani.add(Integer.parseInt(aC12.getText()));
        }
        if(a13.isSelected()){
            aC13.setEditable(true);
            ani.add(Integer.parseInt(aC13.getText()));
        }else{
            ani.add(0);
        }

        for(int i=0; i<ani.size(); i++){
            all+=ani.get(i);
        }
        result.setText(all+"");
    }//GEN-LAST:event_allAniActionPerformed

    private void clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllActionPerformed
        // TODO add your handling code here:
        result.setText("");
    }//GEN-LAST:event_clearAllActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed
        int Peas = 25,Bcorn = 10,Grass = 9,Cab = 11,Ban = 17;
        double Peas1 = 12.4,Bcorn1 = 17.8;
    private void Combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo1ActionPerformed
        // TODO add your handling code here:
        String val = (String)Combo1.getSelectedItem();
        if(val.equals("Select...")){
            q1.setText("");
        }else if(val.equals("Peas")){
            q1.setText(Integer.toString(Peas));
        } if(val.equals("Grass")){
            q1.setText(Integer.toString(Grass));
        }else if(val.equals("Cabbage")){
            q1.setText(Integer.toString(Cab));
        }else if(val.equals("Banana")){
            q1.setText(Integer.toString(Ban));
        }else if(val.equals("Baby Corn")){
            q1.setText(Integer.toString(Bcorn));
        }
    }//GEN-LAST:event_Combo1ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void totalVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalVegActionPerformed

    private void q2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_q2MouseClicked
    int B = 35,C = 23,M = 17,F = 12;
    private void Combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo2ActionPerformed
        // TODO add your handling code here:
        String vall = (String)Combo2.getSelectedItem();
        if(vall.equals("Select...")){
            q3.setText("");
        }else if(vall.equals("Beef")){
            q3.setText(Integer.toString(B));
        }else if(vall.equals("Chicken")){
            q3.setText(Integer.toString(C));
        }else if(vall.equals("Mutton")){
            q3.setText(Integer.toString(M));
        }else if(vall.equals("Fish")){
            q3.setText(Integer.toString(F));
        }
    }//GEN-LAST:event_Combo2ActionPerformed

    private void q2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_q2KeyPressed
        // TODO add your handling code here:
        int x = Integer.parseInt(q1.getText());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {    
        int y = Integer.parseInt(q2.getText());
        n1.setText(String.valueOf(x-y));
            }  
    }//GEN-LAST:event_q2KeyPressed

    private void totalMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMeatActionPerformed

    private void q4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_q4KeyPressed
        // TODO add your handling code here:
        int x = Integer.parseInt(q3.getText());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {    
        int y = Integer.parseInt(q4.getText());
        n2.setText(String.valueOf(x-y));
            }  
    }//GEN-LAST:event_q4KeyPressed
        public static int d;
    private void totalVegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalVegMouseClicked
        // TODO add your handling code here:
        vegT.setText(String.valueOf(Integer.parseInt(n1.getText())*Double.parseDouble(p1.getText())));
        try{
        File Reg = new File("Vegetable Prices.txt");
        FileWriter f = new FileWriter(Reg,true);
        BufferedWriter wri = new BufferedWriter(f);
        PrintWriter pri = new PrintWriter(wri);
        pri.println(Double.parseDouble(vegT.getText())+" taka");
        pri.close();
        }catch(Exception e) {
         e.printStackTrace();
      }
    }//GEN-LAST:event_totalVegMouseClicked
    
    private void totalMeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMeatMouseClicked
        // TODO add your handling code here:
        meatT.setText(String.valueOf(Integer.parseInt(n2.getText())*Double.parseDouble(p2.getText())));
        try{
        File Reg = new File("Heavy Food Prices.txt");
        FileWriter f = new FileWriter(Reg,true);
        BufferedWriter wri = new BufferedWriter(f);
        PrintWriter pri = new PrintWriter(wri);
        pri.println(Double.parseDouble(meatT.getText())+" taka");
        pri.close();
        }catch(Exception e) {
         e.printStackTrace();
      }
    }//GEN-LAST:event_totalMeatMouseClicked

    private void totalMeatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMeatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMeatMouseEntered

    private void clearTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextFActionPerformed
        // TODO add your handling code here:
        receipt.setText("");
    }//GEN-LAST:event_clearTextFActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ArrayList<String[]> Vpri = new ArrayList<>();
        String vline = null;
        double VegSum=0;
        try{
            BufferedReader vb = new BufferedReader(new FileReader("Vegetable Prices.txt"));
            while((vline = vb.readLine()) != null){
                Vpri.add(vline.split(" taka"));
            }
        }catch(Exception e) {
         e.printStackTrace();
        }     for(int i=0; i<Vpri.size(); i++){
                VegSum += Double.parseDouble(Vpri.get(i)[0]);
        }
        
        ArrayList<String[]> Mpri = new ArrayList<>();
        String mline = null;
        double MeatSum=0;
        try{
            BufferedReader mb = new BufferedReader(new FileReader("Heavy Food Prices.txt"));
            while((mline = mb.readLine()) != null){
                Mpri.add(mline.split(" taka"));
            }
        }catch(Exception e) {
         e.printStackTrace();
        }     for(int i=0; i<Mpri.size(); i++){
                MeatSum += Double.parseDouble(Mpri.get(i)[0]);
        }
        double t = VegSum + MeatSum;
        receipt.setText("\t  ZOO MANAGEMENT\n\n"+"Animals In Total\t"+String.valueOf(result.getText())+"\n"
                        +"Vegetables Total\t\t "+String.valueOf(VegSum)+" ৳\n"
                        +"Meat Total\t\t\t "+String.valueOf(MeatSum)+" ৳\n"
                        +"------------------------------------------------------------------\n"
                        +"Total food cost\t\t "+String.valueOf(t)+" ৳\n"
                        +"\n\t\t\tThank You");
    }//GEN-LAST:event_jButton1MouseClicked

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close2ActionPerformed

    private void SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseClicked
        // TODO add your handling code here:
        zLogin z = new zLogin();
        z.setVisible(true);
        z.pack();
        z.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SignOutMouseClicked

    private void close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close3ActionPerformed

    private void ownerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerBActionPerformed
        // TODO add your handling code here:
        if(ownerB.isSelected()){
            managerB.setSelected(false);
            policeB.setSelected(false);
        }
    }//GEN-LAST:event_ownerBActionPerformed

    private void managerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBActionPerformed
        // TODO add your handling code here:
        if(managerB.isSelected()){
            ownerB.setSelected(false);
            policeB.setSelected(false);
        }
    }//GEN-LAST:event_managerBActionPerformed

    private void policeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeBActionPerformed
        // TODO add your handling code here:
        if(policeB.isSelected()){
            managerB.setSelected(false);
            ownerB.setSelected(false);
        }
    }//GEN-LAST:event_policeBActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(ownerB.isSelected()){
            JOptionPane.showMessageDialog(null,"Calling Zoo Owner . . .");
        }
        if(managerB.isSelected()){
            JOptionPane.showMessageDialog(null,"Calling Zoo Manager . . .");
        }
        if(policeB.isSelected()){
            JOptionPane.showMessageDialog(null,"Calling Police . . .");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zSystem().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Animal;
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private javax.swing.JPanel Emergency;
    private javax.swing.JPanel Food;
    private javax.swing.JTabbedPane JTabbedPanel;
    private javax.swing.JPanel Receipt;
    private javax.swing.JButton SignOut;
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a10;
    private javax.swing.JCheckBox a11;
    private javax.swing.JCheckBox a12;
    private javax.swing.JCheckBox a13;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JCheckBox a5;
    private javax.swing.JCheckBox a6;
    private javax.swing.JCheckBox a7;
    private javax.swing.JCheckBox a8;
    private javax.swing.JCheckBox a9;
    private javax.swing.JTextField aC1;
    private javax.swing.JTextField aC10;
    private javax.swing.JTextField aC11;
    private javax.swing.JTextField aC12;
    private javax.swing.JTextField aC13;
    private javax.swing.JTextField aC2;
    private javax.swing.JTextField aC3;
    private javax.swing.JTextField aC4;
    private javax.swing.JTextField aC5;
    private javax.swing.JTextField aC6;
    private javax.swing.JTextField aC7;
    private javax.swing.JTextField aC8;
    private javax.swing.JTextField aC9;
    private javax.swing.JButton allAni;
    private javax.swing.JButton clearAll;
    private javax.swing.JButton clearTextF;
    private javax.swing.JButton close;
    private javax.swing.JButton close2;
    private javax.swing.JButton close3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton managerB;
    private javax.swing.JTextField managerN;
    private javax.swing.JTextField meatT;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JRadioButton ownerB;
    private javax.swing.JTextField ownerN;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JRadioButton policeB;
    private javax.swing.JTextField policeN;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextArea receipt;
    private javax.swing.JTextField result;
    private javax.swing.JButton totalMeat;
    private javax.swing.JButton totalVeg;
    private javax.swing.JTextField vegT;
    // End of variables declaration//GEN-END:variables
}
